steps:
  - name: maven
    entrypoint: mvn
    args: ['clean', 'install', '-DskipTests']
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-east1-docker.pkg.dev/sandbox-io-289003/taj-app-1", "--build-arg=JAR_FILE=target/spring-boot-docker.jar", "." ]
images: ["us-east1-docker.pkg.dev/sandbox-io-289003/taj-app-1"]
#   # push the container image
# - name: "gcr.io/cloud-builders/docker"
#   args: ["push", "gcr.io/sandbox-io-289003/image:tag"]
#   # deploy container image to kubernetes
# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=kubernetes-resource-file
#   - --image=gcr.io/project-id/image:tag
#   - --location=location
#   - --cluster=cluster