apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: taji-hc-config
spec:
  logging:
    enable: true
    sampleRate: 0.5
  healthCheck:
    checkIntervalSec: 15
    port: 8080
    type: HTTP
    requestPath: /taji/api/hello